language: python
dist: trusty
python:
  - "3.5"
# command to install dependencies
install: "pip install shapely matplotlib"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/python
#  - echo $PYTHONPATH
#  - ls -la
#  - ls -la python
# command to run tests
script: 
#  - echo $PYTHONPATH
#  - ls -la
#  - ls -la python
#  - "python python/tests/test1.py"
  #- "python python/tests/test2.py"  
  - "python python/tests/manufacturing_example1.py"
  - "python python/tests/manufacturing_example2.py"
  - "python python/tests/manufacturing_example3.py"
  - "python python/tests/manufacturing_example4.py"
  